# Generated by Django 5.2 on 2025-05-31 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_projectevent_trackprojectuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectevent",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
