# Generated by Django 5.2 on 2025-05-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_comment_project_projectprogress_projectuser_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="progress_id",
            new_name="progress",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="projectprogress",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="projectuser",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="projectuser",
            old_name="user_id",
            new_name="user",
        ),
    ]
