# Generated by Django 5.2 on 2025-05-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rename_progress_id_comment_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("done", "Done"),
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                ],
                max_length=20,
            ),
        ),
    ]
