# Generated by Django 5.2 on 2025-05-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_project_status_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("done", "Done"),
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                ],
                max_length=20,
            ),
        ),
    ]
