# Generated by Django 5.2 on 2025-05-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_projectprogress_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("professor", "Professor"),
                    ("student", "Student"),
                    ("admin", "Admin"),
                ],
                max_length=10,
            ),
        ),
    ]
