# Generated by Django 5.2 on 2025-05-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_project_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
