# Generated by Django 5.2 on 2025-05-28 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_project_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectprogress",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="myapp.user"
            ),
        ),
    ]
